### ISSUE TITLE
dear java devs,

### ISSUE THREAD

**Issue by jnmandal** [austent89/ScalaUtilities#1]
don't you know that node.js is pretty sweet? 

what is going on? don't you know NFLX uses node.js? what's more, many people on quora say it is better.

![https://media.giphy.com/media/wpoLqr5FT1sY0/giphy.gif](https://media.giphy.com/media/wpoLqr5FT1sY0/giphy.gif)

**Comment by austent89** [comment]
Node.js is prettay sweet.
